### ISSUE TITLE
Enable on every pages

### ISSUE THREAD

**Issue by gloomy-ghost** [asamuzaK/url2clipboard#11]
I think that disabling on non-HTML documents doesn't worth a scary `Access your data for all websites` permission, since I don't even know why are we disabling it.

My suggestion is to just simply enable all of them at startup. The content script can be inserted by using `tabs.executeScript` when a user action is raised and we need to show a confirm. This approach only needs the `activeTab` permission, and we can remove the `content_scripts` for `<all_urls>` in the manifest.

**Comment by asamuzaK** [comment]
It need to detect if user is pointing at the anchor element or not *before* context menu is shown. (Context menu can't update dynamically after it is shown).
Which means content script need to be attached to all pages, and listen to mouse or keyboard event.

So

> The content script can be inserted by using `tabs.executeScript` when a user action is raised and we need to show a confirm.

can't be an option.

BTW, while I was checking this issue, I noticed it can be enabled on some non-HTML documents / binary files for example .png files.
It is because browser wraps those documents in there internal HTML.
On the other hand, I found it throws when executeCommand() on SVG documents.
I misunderstood that executeCommand can also be executed in XML.
That is fixed in this commit. [Enable only on HTMLDocument · asamuzaK/url2clipboard@d0ee74c](https://github.com/asamuzaK/url2clipboard/commit/d0ee74c15c5d8332f0a1cae9316e87d943ac88b9 "Enable only on HTMLDocument · asamuzaK/url2clipboard@d0ee74c")
